CICS ^(2|4|5|6|1[2345])$
GlobalCache ^(2|4|5|6|1[6-9]|[2-9][0-9])$
JMS ^(2|4|5|6)$
JVM ^(2|4|5|6)$
Parsers ^(2|4|5|6|1[789]|[2-9][0-9]|[1-9][0-9]{2})$
SOAPInput ^(2|4|5|6)$
TCPIPServerNodes ^(2|4|5|6)$
TCPIPClientNodes ^(2|4|5|6)$